spring.application.name=job_management_system

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/job_db
spring.datasource.username=postgres
spring.datasource.password=neophenon!@#

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.cache.type=redis
spring.redis.host=localhost
spring.redis.port=6379
spring.redis.password=job_redis_containerForProdigiousDataFetching